import { Field } from './types';

const defaultFields: Field[] = [
  {
    id: '1',
    required: true,
    label: 'Full Name (as per NRIC)',
    type: 'short_ans',
    order: 1,
    defaultField: true,
    normalizedLabel: 'fullname',
    placeholder: 'Full Name',
  },
  {
    id: '2',
    required: true,
    label: 'APU Email',
    type: 'short_ans',
    order: 2,
    defaultField: true,
    normalizedLabel: 'email',
    placeholder: 'APU Email',
  },
  {
    id: '3',
    required: true,
    label: 'Student ID',
    type: 'short_ans',
    order: 3,
    defaultField: true,
    normalizedLabel: 'apkey',
    placeholder: 'Student ID (e.g., TPXXXXXX)',
  },
  {
    id: '4',
    required: true,
    label: 'Gender',
    type: 'dropdown',
    options: ['Male', 'Female'],
    order: 4,
    defaultField: true,
    normalizedLabel: 'gender',
  },
  {
    id: '5',
    required: true,
    label: 'Contact Number',
    type: 'short_ans',
    order: 5,
    defaultField: true,
    normalizedLabel: 'contact',
    placeholder: 'Contact Number (e.g., +60123456789)',
  },
  {
    id: '6',
    required: true,
    label: 'Intake',
    type: 'short_ans',
    order: 6,
    defaultField: true,
    normalizedLabel: 'intake',
    placeholder: 'Intake (e.g., APU2F2302SE)',
  },
  {
    id: '7',
    required: true,
    label: 'Course of Study',
    type: 'short_ans',
    order: 6,
    defaultField: true,
    normalizedLabel: 'course',
    placeholder: 'Course of Study (e.g., BSc (Hons) in Computing)',
  },
];

export default defaultFields;
