exports.defaultFields = [
  {
    required: true,
    label: 'Full Name (as per NRIC)',
    type: 'short_ans',
    order: 1,
    defaultField: true,
    normalizeLabel: 'fullname',
  },
  {
    required: true,
    label: 'APU Email',
    type: 'short_ans',
    order: 2,
    defaultField: true,
    normalizeLabel: 'email',
  },
  {
    required: true,
    label: 'Student ID',
    type: 'short_ans',
    order: 3,
    defaultField: true,
    normalizeLabel: 'apkey',
  },
  {
    required: true,
    label: 'Gender',
    type: 'dropdown',
    options: ['Male', 'Female'],
    order: 4,
    defaultField: true,
    normalizeLabel: 'gender',
  },
  {
    required: true,
    label: 'Contact Number',
    type: 'short_ans',
    order: 5,
    defaultField: true,
    normalizeLabel: 'contact',
  },
  {
    required: true,
    label: 'Course of Study',
    type: 'short_ans',
    order: 6,
    defaultField: true,
    normalizeLabel: 'course',
  },
];
